# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  bitwarden:
    image: docker.io/bitwarden/self-host:2024.9.2-beta@sha256:8d90075358899c5d35e6210ef41a18428533f81d44edb17e860b04d4294f3d37
    env_file:
      - /etc/bitwarden/settings.env
    # https://bitwarden.com/help/environment-variables/
    environment:
      BW_DOMAIN: "bitwarden.hayzen.uk"
      # Use sqlite
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/vault.db"
      # Disable account registration
      #
      # Allow for now to setup accounts
      globalSettings__disableUserRegistration: true
      # TODO: https?
    expose:
      - "8080"
    mem_limit: 1024m
    restart: unless-stopped
    volumes:
      # Bitwarden uses uid 1000, so use our mapped folder
      - /var/lib/docker-compose-runner-user1000/bitwarden/config:/etc/bitwarden
