# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  bitwarden:
    image: ghcr.io/bitwarden/self-host:2025.2.1-beta@sha256:54752399d72a4559805cb1ee0152a64e5da8acfe4929c7419a0eac8ba9813ba2
    env_file:
      - /etc/bitwarden/settings.env
    # https://bitwarden.com/help/environment-variables/
    environment:
      BW_DOMAIN: "bitwarden.hayzen.uk"
      # Use sqlite
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/vault.db"
      # Disable account registration
      #
      # Allow for now to setup accounts
      globalSettings__disableUserRegistration: true
      # TODO: https?
    expose:
      - "8080"
    mem_limit: 1024m
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # Bitwarden uses uid 1000, so use our mapped folder
      - /var/lib/docker-compose-runner-user1000/bitwarden/config:/etc/bitwarden
