# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: docker.io/actualbudget/actual-server:24.10.0@sha256:85e1ac10bd05bad1e016fdc5a91141d39fb2fe8b5a9e01d8d1c46b4353e7f45f
    expose:
      - "5006"
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data
