# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: docker.io/actualbudget/actual-server:24.9.0@sha256:90a670b73ce539ca4bf70e3740756f106ec815d3933cabf2414ae2e26e031d65
    expose:
      - "5006"
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data
