# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  sftpgo:
    image: docker.io/drakkan/sftpgo:v2.6.4@sha256:42ef940421b43f9651a0dacf882ac6467cee32a74f8d213617daf3c0ebf74344
    environment:
      # Allow for connections to continue for 5s before killing
      SFTPGO_GRACE_TIME: 5
      # Disable SFTP
      SFTPGO_SFTPD__BINDINGS__0__PORT: 0
      # Set root for web gui
      SFTPGO_HTTPD__WEB_ROOT: "/"
      # Enable WebDAV
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 8090
      SFTPGO_WEBDAVD__BINDINGS__0__PREFIX: "/"
    expose:
      - 8080
      - 8090
    networks:
      - group-proxy
      # Needed for exposing webdav locally
      - lan
    ports:
      - "8090:8090"
    restart: unless-stopped
    volumes:
      # SFTP backups
      - /mnt/mapping-data-user1000/app/sftpgo/backups:/srv/sftpgo/backups
      # SFTPGo home
      - /mnt/mapping-data-user1000/user:/srv/sftpgo/data
      # SFTP settings
      - /var/lib/docker-compose-runner-user1000/sftpgo:/var/lib/sftpgo
      # Other data
      - /mnt/mapping-data-user1000/camera:/mnt/data/camera
      - /mnt/mapping-data-user1000/documents:/mnt/data/documents
      - /mnt/mapping-data-user1000/music:/mnt/data/music
      - /mnt/mapping-data-user1000/movies:/mnt/data/movies
      - /mnt/mapping-data-user1000/recordings:/mnt/data/recordings
      - /mnt/mapping-data-user1000/shows:/mnt/data/shows
