# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:2025031705@sha256:66258b3df2e5255590fd03c94458c032a8653d2ea7e4134267a5b9e1a9d67c5f
    restart: unless-stopped
    # For hardware acceleration
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      # HTTP port
      - 8096:8096
      # Auto discovery
      - "7359:7359/udp"
    group_add:
      # GID of render: `getent group render | cut -d: -f3`
      - "303"
    environment:
      # Set the path for discovery
      JELLYFIN_PublishedServerUrl: "http://lab-jonsbo-n3.local:8096"
    networks:
      - group-proxy
      # Needed for auto discovery and local lan quick path
      - lan
    volumes:
      # Jellyfin cache
      - /mnt/pool/cache/jellyfin/cache:/cache
      # Jellyfin config
      #
      # TODO: can we snapshot databases and data with a cache/lib split?
      - /var/lib/docker-compose-runner/jellyfin/config:/config
      # Access media directories
      - /mnt/pool/data/music:/mnt/data/music:ro
      - /mnt/pool/data/movies:/mnt/data/movies:ro
      - /mnt/pool/data/shows:/mnt/data/shows:ro
      - /mnt/pool/data/recordings:/mnt/data/recordings:ro
