# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  vikunja:
    image: docker.io/vikunja/vikunja:2.4@sha256:1a5dd2d410b5359f689c77bbd1c66742cde1993f82d4adfe9aefa400ff1dd833
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.hayzen.uk/
      VIKUNJA_SERVICE_TIMEZONE: "Europe/London"
      # Use sqlite database
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_DATABASE_TYPE: sqlite
      # Disable account registration
      #
      # Note use the CLI to manage accounts
      # https://vikunja.io/docs/cli/#user
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
    env_file:
      - /etc/vikunja/settings_secrets.env
    expose:
      - 3456
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # Uploaded files
      - /mnt/mapping-pool-user1000/data/app/vikunja/files:/app/vikunja/files
      # Database
      - /var/cache/docker-compose-runner-user1000/vikunja/db:/db

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.vikunja.yml:/etc/traefik/dynamic/traefik.vikunja.yml:ro
