# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  # Reverse proxy to other services
  caddy:
    image: caddy:2.8.4@sha256:2c7c4a3b9534b34d598a02e7d2be61d3b3355fb77245aea43c27c6d93e09d55f
    restart: unless-stopped
    cap_add:
      # Allow for increasing buffer size for HTTP/3
      - NET_ADMIN
    links:
      - rathole
    ports:
      - "80:80"
      - "443:443"
      # For HTTP/3
      - "443:443/udp"
    volumes:
      # Caddy configuration file
      - /etc/caddy/Caddyfile.1:/etc/caddy/Caddyfile:ro

      # Flathub stats data
      - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

      # Persistent data (eg TLS storage)
      - /var/lib/docker-compose-runner/caddy/persistent:/data
      # Persistent configuration
      - /var/lib/docker-compose-runner/caddy/config:/config

  # TODO: flathub_stats service
  # - /var/lib/docker-compose-runner/flathub-stats/cache:/var/cache/flathub_stats
  # - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

  rathole:
    image: docker.io/rapiz1/rathole:v0.5.0@sha256:a31b9178e985d4a84f46d4c3af6aa200ee0c5e7f821c7075a1f6669fb77392b1
    command: --server /etc/rathole/config.toml
    expose:
      # Bitwarden
      - "8080"
      # Actual
      - "8506"
      # DSAudio
      - "8801"
      # DSVideo
      - "8808"
    ports:
      # Expose the server
      - "8333:8333"
      # Expose OpenVPN
      - "9194:9194"
    volumes:
      - /etc/rathole/config.1.toml:/etc/rathole/config.toml:ro
