# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  # Reverse proxy to other services
  caddy:
    image: caddy:2.8.4@sha256:9a8e0e6f0f0af954626903b1ae5aac3536f45222131c01e1f2433e8b1ecb3937
    restart: unless-stopped
    cap_add:
      # Allow for increasing buffer size for HTTP/3
      - NET_ADMIN
    links:
      - rathole
      - wagtail-ahayzen
      - wagtail-yumekasaito
    ports:
      - "80:80"
      - "443:443"
      # For HTTP/3
      - "443:443/udp"
    volumes:
      # Caddy configuration file
      - /etc/caddy/Caddyfile.1:/etc/caddy/Caddyfile:ro

      # Flathub stats data
      - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

      # Persistent data (eg TLS storage)
      - /var/lib/docker-compose-runner/caddy/persistent:/data
      # Persistent configuration
      - /var/lib/docker-compose-runner/caddy/config:/config

      # Wagtail media data
      - /var/lib/docker-compose-runner/wagtail-ahayzen/media:/srv/wagtail-ahayzen/media:ro
      # Wagtail static data
      - /var/lib/docker-compose-runner/wagtail-ahayzen/static:/srv/wagtail-ahayzen/static:ro

      # Wagtail media data
      - /var/lib/docker-compose-runner/wagtail-yumekasaito/media:/srv/wagtail-yumekasaito/media:ro
      # Wagtail static data
      - /var/lib/docker-compose-runner/wagtail-yumekasaito/static:/srv/wagtail-yumekasaito/static:ro

  # TODO: flathub_stats service
  # - /var/lib/docker-compose-runner/flathub-stats/cache:/var/cache/flathub_stats
  # - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

  rathole:
    image: docker.io/rapiz1/rathole:v0.5.0@sha256:a31b9178e985d4a84f46d4c3af6aa200ee0c5e7f821c7075a1f6669fb77392b1
    command: --server /etc/rathole/config.toml
    expose:
      # Bitwarden
      - "8080"
      # Actual
      - "8506"
      # DSAudio
      - "8801"
      # DSVideo
      - "8808"
    ports:
      # Expose the server
      - "8333:8333"
      # Expose OpenVPN
      - "9194:9194"
    volumes:
      - /etc/rathole/config.1.toml:/etc/rathole/config.toml:ro

  # Wagtail
  wagtail-ahayzen:
    image: registry.gitlab.com/ahayzen/ahayzen.com/wagtail-image:latest@sha256:3ac663424fdc3cf0fda1c41244c35198322579d52ed5f675ac8ea778160ada0e
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      # Wagtail sqlite database
      - /var/lib/docker-compose-runner/wagtail-ahayzen/db:/srv/webapp/db
      # Wagtail media data
      - /var/lib/docker-compose-runner/wagtail-ahayzen/media:/srv/webapp/media
      # Wagtail static data
      - /var/lib/docker-compose-runner/wagtail-ahayzen/static:/srv/webapp/static
      # Wagtail local settings file
      - /etc/ahayzen.com/local.1.py:/srv/webapp/ahayzen.com/ahayzen/settings/local.py:ro
      # Wagtail docs folder
      - /var/lib/docker-compose-runner/wagtail-ahayzen/docs:/srv/webapp/docs

  wagtail-yumekasaito:
    image: registry.gitlab.com/ahayzen/yumekasaito.com/wagtail-image:latest@sha256:2fc1f8eb6e1458c9c175e63178136f9a3f4ec8b83609573cf0fb76cbf5d20ea8
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      # Wagtail sqlite database
      - /var/lib/docker-compose-runner/wagtail-yumekasaito/db:/srv/webapp/db
      # Wagtail media data
      - /var/lib/docker-compose-runner/wagtail-yumekasaito/media:/srv/webapp/media
      # Wagtail static data
      - /var/lib/docker-compose-runner/wagtail-yumekasaito/static:/srv/webapp/static
      # Wagtail local settings file
      - /etc/yumekasaito.com/local.1.py:/srv/webapp/yumekasaito.com/yumekasaito/settings/local.py:ro
