# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

http:
  routers:
    wg-easy:
      rule: Host(`wg-easy.hayzen.uk`)
      service: wg-easy

  services:
    wg-easy:
      loadBalancer:
        servers:
          - url: http://wg-easy:80

