# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/home-hayzen-uk.Caddyfile:/etc/caddy/sites/home-hayzen-uk.Caddyfile:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.2@sha256:94537770bcf7cd4ded8f2619ab67e0c769b0ca20d7bb997af1e001d5863b6cdf
    expose:
      - "3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.hayzen.uk
      LOG_TARGETS: stdout
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # homepage likes to write missing files, so allow it to write them
      # and mount in our static files
      - /var/lib/docker-compose-runner/homepage/config:/app/config
      - /etc/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - /etc/homepage/services.yaml:/app/config/services.yaml:ro
      - /etc/homepage/settings.yaml:/app/config/settings.yaml:ro
      - /etc/homepage/widgets.yaml:/app/config/widgets.yaml:ro
