# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    links:
      - homepage
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/homepage.Caddyfile:/etc/caddy/sites/homepage.Caddyfile:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.4@sha256:85cd217721b376bf5d84e867b16db10348068bfeb95e033039189b272f904caa
    expose:
      - "3000"
    environment:
      LOG_TARGETS: stdout
    restart: unless-stopped
    volumes:
      # homepage likes to write missing files, so allow it to write them
      # and mount in our static files
      - /var/lib/docker-compose-runner/homepage/config:/app/config
      - /etc/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - /etc/homepage/services.yaml:/app/config/services.yaml:ro
      - /etc/homepage/settings.yaml:/app/config/settings.yaml:ro
      - /etc/homepage/widgets.yaml:/app/config/widgets.yaml:ro
