# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    links:
      - homepage
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/home-hayzen-uk.Caddyfile:/etc/caddy/sites/home-hayzen-uk.Caddyfile:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.9@sha256:4d8500d84e9c73dcfbe913ea92a16321e682c0460f0c005ab2ca6e5d399c2dca
    expose:
      - "3000"
    environment:
      LOG_TARGETS: stdout
    restart: unless-stopped
    volumes:
      # homepage likes to write missing files, so allow it to write them
      # and mount in our static files
      - /var/lib/docker-compose-runner/homepage/config:/app/config
      - /etc/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - /etc/homepage/services.yaml:/app/config/services.yaml:ro
      - /etc/homepage/settings.yaml:/app/config/settings.yaml:ro
      - /etc/homepage/widgets.yaml:/app/config/widgets.yaml:ro
