# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/home-hayzen-uk.Caddyfile:/etc/caddy/sites/home-hayzen-uk.Caddyfile:ro

  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13@sha256:396356a07e05d904a233ed54358ffd1cccbd6e57f1a7148bcf88d88cedaa4c25
    expose:
      - "3000"
    environment:
      LOG_TARGETS: stdout
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # homepage likes to write missing files, so allow it to write them
      # and mount in our static files
      - /var/lib/docker-compose-runner/homepage/config:/app/config
      - /etc/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - /etc/homepage/services.yaml:/app/config/services.yaml:ro
      - /etc/homepage/settings.yaml:/app/config/settings.yaml:ro
      - /etc/homepage/widgets.yaml:/app/config/widgets.yaml:ro
