# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0
---

- Media:
    - Immich:
        href: https://immich.ahayzen.com/
        icon: immich.png
        description: "Self-hosted photo and video management solution"
        siteMonitor: "http://rathole:8301"

- Utilities:
    - Actual:
        href: https://actual.ahayzen.com/
        icon: actual.png
        description: "Your Finances - made simple"
        siteMonitor: "http://rathole:8506"

    - Bitwarden:
        href: https://bitwarden.ahayzen.com/
        icon: bitwarden.png
        description: "The #1 most trusted password manager"
        siteMonitor: "http://rathole:8080"
