# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0
---

- Media:
    - Immich:
        href: https://home.hayzen.uk/immich/
        icon: immich.png
        description: "Self-hosted photo and video management solution"
        siteMonitor: https://immich.ahayzen.com/

- Utilities:
    - Actual:
        href: https://home.hayzen.uk/actual/
        icon: actual.png
        description: "Your Finances - made simple"
        siteMonitor: https://actual.ahayzen.com/

    - Bitwarden:
        href: https://home.hayzen.uk/bitwarden/
        icon: bitwarden.png
        description: "The #1 most trusted password manager"
        siteMonitor: https://bitwarden.ahayzen.com/
