# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0
---

- Files:
    - SFTPGo:
        href: https://sftpgo.hayzen.uk/
        icon: sftpgo.png
        description: "Bring your file transfers anywhere"
        siteMonitor: "http://rathole:8880"

    - WebDav:
        href: https://webdav.hayzen.uk/
        icon: webdav.png
        description: "Web-based Distributed Authoring and Versioning"
        siteMonitor: "http://rathole:8890"

- Media:
    - Immich:
        href: https://immich.hayzen.uk/
        icon: immich.png
        description: "Self-hosted photo and video management solution"
        siteMonitor: "http://rathole:8301"

    - Jellyfin:
        href: https://jellyfin.hayzen.uk/
        icon: jellyfin.png
        description: "The Free Software Media System"
        siteMonitor: "http://rathole:8896"

- Utilities:
    - Actual:
        href: https://actual.ahayzen.com/
        icon: actual.png
        description: "Your Finances - made simple"
        siteMonitor: "http://rathole:8506"

    - Bitwarden:
        href: https://bitwarden.hayzen.uk/
        icon: bitwarden.png
        description: "The #1 most trusted password manager"
        siteMonitor: "http://rathole:8080"
