# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  glances:
    image: docker.io/nicolargo/glances:4.5.0@sha256:837c4c5c3d0f636116868fddeca7075781457449311efd10c880037f41ce55f7
    environment:
      - "GLANCES_OPT=-w -C /etc/glances/glances.conf"
    expose:
      - "61208"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /etc/glances/glances.conf:/etc/glances/glances.conf:ro
      - /etc/os-release:/etc/os-release:ro
      - /mnt/pool/cache:/mnt/pool/cache:ro
