# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: ghcr.io/actualbudget/actual:26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
    environment:
      # Trust traefik, group-proxy, and VPN tunnel
      ACTUAL_TRUSTED_PROXIES: "172.20.20.0/24,172.28.228.128/25"
    expose:
      - "5006"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.actual.yml:/etc/traefik/dynamic/traefik.actual.yml:ro
