# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: ghcr.io/actualbudget/actual:26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
    environment:
      # Trust traefik, group-proxy, and VPN tunnel
      ACTUAL_TRUSTED_PROXIES: "172.20.20.0/24,172.28.228.128/25"
    expose:
      - "5006"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.actual.yml:/etc/traefik/dynamic/traefik.actual.yml:ro
