# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: ghcr.io/actualbudget/actual:25.5.0@sha256:3b486fbc0db02839917f65ed277aa509980f710b6e96dde966f5219983978179
    expose:
      - "5006"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data
