# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: ghcr.io/actualbudget/actual:26.8.0@sha256:0b300f370dba85a74998a953736a831bd931cc8cb76c0d8ceac3d3fd288dfd4d
    environment:
      # Trust traefik, group-proxy, and VPN tunnel
      ACTUAL_TRUSTED_PROXIES: "172.20.20.0/24,172.28.228.128/25"
    expose:
      - "5006"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.actual.yml:/etc/traefik/dynamic/traefik.actual.yml:ro
