# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: ghcr.io/actualbudget/actual:26.2.0@sha256:9127ac149f96a6c17ab811203f8f6c27acacc5a49f1620badec7797ca4ac5537
    expose:
      - "5006"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data
