# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/ntfy.Caddyfile:/etc/caddy/sites/ntfy.Caddyfile:ro

  ntfy:
    image: docker.io/binwiederhier/ntfy:v2.15@sha256:aa10e84da624f65be107f9317dbf6e212fa812e0ebf62e74d032d0762eccc930
    command:
      - serve
    environment:
      TZ: Europe/London
      NTFY_BASE_URL: https://ntfy.hayzen.uk
      NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
      NTFY_CACHE_DURATION: 72h
      NTFY_AUTH_FILE: /var/cache/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_REQUIRE_LOGIN: true
    env_file:
      - /etc/ntfy/auth_secrets.env
    networks:
      - group-services
    volumes:
      - /var/cache/docker-compose-runner/ntfy:/var/cache/ntfy
    expose:
      - "80"
    restart: unless-stopped
