# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  glances:
    image: docker.io/nicolargo/glances:4.2.0@sha256:a7c7487cb74ebfe2e34d940432e09718a4d952dce7d76b971585f60f6b7319cb
    environment:
      - "GLANCES_OPT=-w"
    expose:
      - "61208"
    restart: unless-stopped
    volumes:
      - /etc/os-release:/etc/os-release:ro
