# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  glances:
    image: docker.io/nicolargo/glances:4.3.0@sha256:a08bb4ee2017c7901b4df9d5cb8c268a39e0ba036b9188d9f6e1d058de0b3ba3
    environment:
      - "GLANCES_OPT=-w"
    expose:
      - "61208"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /etc/os-release:/etc/os-release:ro
