# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  glances:
    image: docker.io/nicolargo/glances:4.5.6@sha256:1d41d61685b620256a8189ca6761129d30c76eb2ef50f100b9dc6265d977f1a3
    environment:
      - "GLANCES_OPT=-w"
    expose:
      - "61208"
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      - /etc/os-release:/etc/os-release:ro
