# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  sftpgo:
    image: ghcr.io/drakkan/sftpgo:v2.7@sha256:24f68c1e6617f3999debde0478f435d375d496c46644b82d3ca154842d4f6c40
    environment:
      # Allow for connections to continue for 5s before killing
      SFTPGO_GRACE_TIME: 5
      # Disable SFTP
      SFTPGO_SFTPD__BINDINGS__0__PORT: 0
      # Set root for web gui
      SFTPGO_HTTPD__WEB_ROOT: "/"
      # Enable WebDAV
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 8090
      SFTPGO_WEBDAVD__BINDINGS__0__PREFIX: "/"
    expose:
      - 8080
      - 8090
    networks:
      - group-proxy
      # Needed for exposing webdav locally
      - lan
    ports:
      - "8090:8090"
    restart: unless-stopped
    volumes:
      # SFTP backups
      - /mnt/mapping-pool-user1000/data/app/sftpgo/backups:/srv/sftpgo/backups
      # SFTPGo home
      - /mnt/mapping-pool-user1000/data/app/sftpgo/user:/srv/sftpgo/data
      # SFTP settings
      - /var/cache/docker-compose-runner-user1000/sftpgo:/var/lib/sftpgo
      # Other data
      - /mnt/mapping-pool-user1000/data/camera:/mnt/data/camera
      - /mnt/mapping-pool-user1000/data/documents:/mnt/data/documents
      - /mnt/mapping-pool-user1000/data/files:/mnt/data/files
      - /mnt/mapping-pool-user1000/data/music:/mnt/data/music
      - /mnt/mapping-pool-user1000/data/movies:/mnt/data/movies
      - /mnt/mapping-pool-user1000/data/recordings:/mnt/data/recordings
      - /mnt/mapping-pool-user1000/data/shows:/mnt/data/shows
      - /mnt/mapping-pool-user1000/data/user:/mnt/data/user
