# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.10.3@sha256:17c3a8d9dddb97789b5f37112840ebf96566442c14d4754193a6c2eb154bc221
    restart: unless-stopped
    # For hardware acceleration
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      # HTTP port
      - 8096:8096
      # Auto discovery
      - "7359:7359/udp"
    environment:
      # Set the path for discovery
      JELLYFIN_PublishedServerUrl: "http://lab.local:8096"
    networks:
      - group-proxy
      # Needed for auto discovery and local lan quick path
      - lan
    volumes:
      # Jellyfin cache
      - /var/cache/docker-compose-runner/jellyfin/cache:/cache
      # Jellyfin config
      - /var/lib/docker-compose-runner/jellyfin/config:/config
      # Access media directories
      - /mnt/data/music:/mnt/data/music:ro
      - /mnt/data/movies:/mnt/data/movies:ro
      - /mnt/data/shows:/mnt/data/shows:ro
      - /mnt/data/recordings:/mnt/data/recordings:ro
