# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:2024080505@sha256:22f6412e204f07663a3a6dfc7021d8e71456b791278985fc176911eb59a3c642
    restart: unless-stopped
    # For hardware acceleration
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      # HTTP port
      - 8096:8096
      # Auto discovery
      - "7359:7359/udp"
    environment:
      # Set the path for discovery
      JELLYFIN_PublishedServerUrl: "http://lab.local:8096"
    volumes:
      # Jellyfin cache
      - /var/cache/docker-compose-runner/jellyfin/cache:/cache
      # Jellyfin config
      - /var/lib/docker-compose-runner/jellyfin/config:/config
      # Access media directories
      - /mnt/data/movies:/mnt/data/movies:ro
      - /mnt/data/shows:/mnt/data/shows:ro
      - /mnt/data/recordings:/mnt/data/recordings:ro
