# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.135.3@sha256:df5bbf4e29eff4688063a005708f8b96f13073200b4a7378f7661568459b31e9
    # From hwaccel.transcoding.yml should allow for VAAPI to work
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Our data
      - /mnt/pool/data/photostream:/usr/src/app/upload/library
      # Other app data that should persist
      - /mnt/pool/data/app/immich:/usr/src/app/upload
      # External libraries
      - /mnt/pool/data/camera:/mnt/data/camera:ro
      - /mnt/pool/data/user/andrew/Camera:/mnt/data/user/andrew/Camera:ro
      - /mnt/pool/data/user/yumeka/Camera:/mnt/data/user/yumeka/Camera:ro
      # Custom locations of internals
      #
      # Profile picture
      - /var/lib/docker-compose-runner/immich/server/profile:/usr/src/app/upload/profile
      # Run generate thumbnail job
      - /mnt/pool/cache/immich/server/thumbs:/usr/src/app/upload/thumbs
      # Run transcode job
      - /mnt/pool/cache/immich/server/encoded-video:/usr/src/app/upload/encoded-video
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    expose:
      - 2283
    depends_on:
      - immich-database
      - immich-redis
    networks:
      - app-immich
      - group-proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.135.3@sha256:9f2f61d86af82d04926f9b896c995c502303052905517c5485dd26bf1e42a44e
    volumes:
      - /var/cache/docker-compose-runner/immich/machine-learning-cache:/cache
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2.19@sha256:3edb1dde146ddde97328306b5d72eabdba7959c53593afcdd2123b5e00df43e6
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - app-immich
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:5f6a838e4e44c8e0e019d0ebfe3ee8952b69afc2809b2c25f7b0119641978e91
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    volumes:
      - /var/cache/docker-compose-runner/immich/postgres:/var/lib/postgresql/data
      - /var/lib/docker-compose-runner/immich/postgres:/var/lib/docker-compose-runner/immich/postgres
    restart: always
