# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.137.3@sha256:e517f806457057d44695152a0af2dfa094225a7d85eb37f518925e68864c658d
    # From hwaccel.transcoding.yml should allow for VAAPI to work
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Our data
      - /mnt/pool/data/photostream:/usr/src/app/upload/library
      # Other app data that should persist
      - /mnt/pool/data/app/immich:/usr/src/app/upload
      # External libraries
      - /mnt/pool/data/camera:/mnt/data/camera:ro
      - /mnt/pool/data/user/andrew/Camera:/mnt/data/user/andrew/Camera:ro
      - /mnt/pool/data/user/yumeka/Camera:/mnt/data/user/yumeka/Camera:ro
      # Custom locations of internals
      #
      # Profile picture
      - /var/lib/docker-compose-runner/immich/server/profile:/usr/src/app/upload/profile
      # Run generate thumbnail job
      - /mnt/pool/cache/immich/server/thumbs:/usr/src/app/upload/thumbs
      # Run transcode job
      - /mnt/pool/cache/immich/server/encoded-video:/usr/src/app/upload/encoded-video
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    expose:
      - 2283
    depends_on:
      - immich-database
      - immich-redis
    networks:
      - app-immich
      - group-proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.137.3@sha256:ef517c041fa4a6a84a6c3c4f88a1124058e686c9c92bf09a973e7e60c3c3ea1e
    volumes:
      - /var/cache/docker-compose-runner/immich/machine-learning-cache:/cache
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2.19@sha256:37440b1f783e3dcabb49eaaaa1bb52a619275072eadf9dadbaa271e5b69bfe2c
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - app-immich
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    volumes:
      - /var/cache/docker-compose-runner/immich/postgres:/var/lib/postgresql/data
      - /var/lib/docker-compose-runner/immich/postgres:/var/lib/docker-compose-runner/immich/postgres
    restart: always
