# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.132.3@sha256:6680d88486251b0264a78a1934fe82eef875555aa6d84d703a0980328a5d5c31
    # From hwaccel.transcoding.yml should allow for VAAPI to work
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Our data
      - /mnt/pool/data/photostream:/usr/src/app/upload/library
      # Other app data that should persist
      - /mnt/pool/data/app/immich:/usr/src/app/upload
      # External libraries
      - /mnt/pool/data/camera:/mnt/data/camera:ro
      - /mnt/pool/data/user/andrew/Camera:/mnt/data/user/andrew/Camera:ro
      - /mnt/pool/data/user/yumeka/Camera:/mnt/data/user/yumeka/Camera:ro
      # Custom locations of internals
      #
      # Profile picture
      - /var/lib/docker-compose-runner/immich/server/profile:/usr/src/app/upload/profile
      # Run generate thumbnail job
      - /mnt/pool/cache/immich/server/thumbs:/usr/src/app/upload/thumbs
      # Run transcode job
      - /mnt/pool/cache/immich/server/encoded-video:/usr/src/app/upload/encoded-video
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    expose:
      - 2283
    depends_on:
      - immich-database
      - immich-redis
    networks:
      - app-immich
      - group-proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.132.3@sha256:f45063889794008cfc02fcf9d359b55fe37d1f8ebaf89653c89e1dd0e876eb7d
    volumes:
      - /var/cache/docker-compose-runner/immich/machine-learning-cache:/cache
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2.18@sha256:e88f17dbd436fa532b0be577b17f8afb3455dea89e04c2a1f50090fb254d3d4b
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - app-immich
    restart: always

  immich-database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    volumes:
      - /var/cache/docker-compose-runner/immich/postgres:/var/lib/postgresql/data
      - /var/lib/docker-compose-runner/immich/postgres:/var/lib/docker-compose-runner/immich/postgres
    #healthcheck:
    #  test: pg_isready --dbname='immich' || exit 1; Chksum="$$(psql --dbname='immich' --username='postgres' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    #  interval: 5m
    #  start_interval: 30s
    #  start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
