# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
    # From hwaccel.transcoding.yml should allow for VAAPI to work
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Our data
      - /mnt/pool/data/photostream:/data/library
      # Other app data that should persist
      - /mnt/pool/data/app/immich:/data
      # External libraries
      - /mnt/pool/data/camera:/mnt/data/camera:ro
      - /mnt/pool/data/user/andrew/Camera:/mnt/data/user/andrew/Camera:ro
      - /mnt/pool/data/user/yumeka/Camera:/mnt/data/user/yumeka/Camera:ro
      # Custom locations of internals
      #
      # Profile picture
      - /var/lib/docker-compose-runner/immich/server/profile:/data/profile
      # Run generate thumbnail job
      - /mnt/pool/cache/immich/server/thumbs:/data/thumbs
      # Run transcode job
      - /mnt/pool/cache/immich/server/encoded-video:/data/encoded-video
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    expose:
      - 2283
    depends_on:
      - immich-database
      - immich-redis
    networks:
      - app-immich
      - group-proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
    volumes:
      - /var/cache/docker-compose-runner/immich/machine-learning-cache:/cache
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    restart: always

  immich-redis:
    container_name: immich_redis
    image: ghcr.io/valkey-io/valkey:8.1.5@sha256:e817820fe9786391a29edb2fc436e2506b5df769299a9547bffeb83518df6c66
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - app-immich
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    volumes:
      - /var/cache/docker-compose-runner/immich/postgres:/var/lib/postgresql/data
      - /var/lib/docker-compose-runner/immich/postgres:/var/lib/docker-compose-runner/immich/postgres
    restart: always
