# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.140.1@sha256:d97aea4b3f59989a79c6adffb39a1a8b95dd27c90a7f79280b1176a6220cf17b
    # From hwaccel.transcoding.yml should allow for VAAPI to work
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Our data
      - /mnt/pool/data/photostream:/data/library
      # Other app data that should persist
      - /mnt/pool/data/app/immich:/data
      # External libraries
      - /mnt/pool/data/camera:/mnt/data/camera:ro
      - /mnt/pool/data/user/andrew/Camera:/mnt/data/user/andrew/Camera:ro
      - /mnt/pool/data/user/yumeka/Camera:/mnt/data/user/yumeka/Camera:ro
      # Custom locations of internals
      #
      # Profile picture
      - /var/lib/docker-compose-runner/immich/server/profile:/data/profile
      # Run generate thumbnail job
      - /mnt/pool/cache/immich/server/thumbs:/data/thumbs
      # Run transcode job
      - /mnt/pool/cache/immich/server/encoded-video:/data/encoded-video
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    expose:
      - 2283
    depends_on:
      - immich-database
      - immich-redis
    networks:
      - app-immich
      - group-proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.140.1@sha256:6239f9852f2ccd8bef52b161629a8fc62bac7636750c06e5fe021e994bab4781
    volumes:
      - /var/cache/docker-compose-runner/immich/machine-learning-cache:/cache
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2.19@sha256:f03dda4477b065b161ac3338645710405c5c9fbecb1c983af495b1b1d444bcd1
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - app-immich
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:8d292bdb796aa58bbbaa47fe971c8516f6f57d6a47e7172e62754feb6ed4e7b0
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    env_file:
      - /etc/immich/settings.env
      - /etc/immich/settings_secrets.env
    networks:
      - app-immich
    volumes:
      - /var/cache/docker-compose-runner/immich/postgres:/var/lib/postgresql/data
      - /var/lib/docker-compose-runner/immich/postgres:/var/lib/docker-compose-runner/immich/postgres
    restart: always
