# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  # Reverse proxy to other services
  caddy:
    image: caddy:2.8.4@sha256:2ae8f7fcd4d82d1c5c1c4dc45ad5f24ab1c1f3af4dd6db03a83d126047d7a939
    restart: unless-stopped
    cap_add:
      # Allow for increasing buffer size for HTTP/3
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      # For HTTP/3
      - "443:443/udp"
    volumes:
      # Caddy configuration file
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

      # Flathub stats data
      - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

      # Persistent data (eg TLS storage)
      - /var/lib/docker-compose-runner/caddy/persistent:/data
      # Persistent configuration
      - /var/lib/docker-compose-runner/caddy/config:/config

  # TODO: flathub_stats service
  # - /var/lib/docker-compose-runner/flathub-stats/cache:/var/cache/flathub_stats
  # - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro
