# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  # Reverse proxy to other services
  caddy:
    image: docker.io/library/caddy:2.9.1@sha256:cd261fc62394f1ff0b44f16eb1d202b4e71d5365c9ec866a4f1a9c5a52da9352
    restart: unless-stopped
    cap_add:
      # Allow for increasing buffer size for HTTP/3
      - NET_ADMIN
    networks:
      - internet
      - group-proxy
      - group-web
    ports:
      - "80:80"
      - "443:443"
      # For HTTP/3
      - "443:443/udp"
    volumes:
      # Caddy configuration file
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

      # Caddy log file
      - /var/log/caddy:/var/log/caddy

      # Flathub stats data
      - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro

      # Persistent data (eg TLS storage)
      - /var/lib/docker-compose-runner/caddy/persistent:/data
      # Persistent configuration
      - /var/lib/docker-compose-runner/caddy/config:/config

  # TODO: flathub_stats service
  # - /var/lib/docker-compose-runner/flathub-stats/cache:/var/cache/flathub_stats
  # - /var/lib/docker-compose-runner/flathub-stats/data:/srv/flathub_stats:ro
