# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  restic-local:
    container_name: restic_local
    image: docker.io/restic/restic:0.17.3@sha256:8f5a62b422a2cb1277ea0dd6e826fe1acf649e5b9f02d60e5268d5fd1976255a
    entrypoint:
      - /bin/sh
    # Check if a repo exists
    # If it doesn't create one
    # Then wait forever to keep the container running so we can exec on it
    command: ["-c", "(/usr/bin/restic cat config || /usr/bin/restic init) && tail -F /dev/null"]
    environment:
      RESTIC_REPOSITORY: /mnt/pool/backup/restic
      RESTIC_PASSWORD_FILE: /etc/restic/password
      XDG_CACHE_HOME: /var/cache
    # Set a host to ensure that caches and settings are correct in restic
    # as docker containers have a new host name every time
    hostname: restic-local
    # Allocate a tty then restic prints more info used for testing
    tty: true
    volumes:
      - /etc/restic/password:/etc/restic/password:ro
      # The source data
      - /mnt/pool/data:/mnt/pool/data:ro
      # The repository
      - /mnt/pool/backup/restic:/mnt/pool/backup/restic:rw
      # Cache uses XDG_CACHE_HOME/restic
      # https://restic.readthedocs.io/en/stable/manual_rest.html#caching
      - /var/cache/docker-compose-runner/restic:/var/cache/restic:rw
