# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  restic-offsite:
    container_name: restic_offsite
    image: ghcr.io/restic/restic:0.18@sha256:c1958a2a1c8614f5c317347c2aaddd9f426076f0521430b55509eba43d7516ee
    entrypoint:
      - /bin/sh
    # Check if a repo exists
    # If it doesn't create one
    # Then wait forever to keep the container running so we can exec on it
    command: ["-c", "(/usr/bin/restic cat config || /usr/bin/restic init) && tail -F /dev/null"]
    env_file:
      - /etc/restic/offsite.env
    environment:
      RESTIC_PASSWORD_FILE: /etc/restic/password
      XDG_CACHE_HOME: /var/cache
    # Set a host to ensure that caches and settings are correct in restic
    # as docker containers have a new host name every time
    hostname: restic-offsite
    networks:
      # Needed to access offsite
      - internet
    # Allocate a tty then restic prints more info used for testing
    tty: true
    volumes:
      - /etc/restic/offsite_env:/etc/restic/offsite_env:ro
      - /etc/restic/password:/etc/restic/password:ro
      # The source data
      - /mnt/pool/data:/mnt/pool/data:ro
      # Cache uses XDG_CACHE_HOME/restic
      # https://restic.readthedocs.io/en/stable/manual_rest.html#caching
      - /var/cache/docker-compose-runner/restic/offsite:/var/cache/restic:rw
