# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

# Note that this is the generated IP address of the test VM
# they are alphabetical, backup, lab, vps
#
# TODO: can we make docker resolve "vps" to this IP?
[client]
remote_addr = "192.168.1.3:8333"
# TODO: if multiple config files were supported, then agenix could contain
# only the token
# https://github.com/rapiz1/rathole/issues/264
default_token = "CHANGEME"

[client.services.actual]
local_addr = "actual:5006"

[client.services.bitwarden]
local_addr = "bitwarden:8080"

[client.services.immich]
local_addr = "immich-server:3001"

[client.services.sftpgo]
local_addr = "sftpgo:8080"
