# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  nextcloud:
    container_name: nextcloud
    image: docker.io/library/nextcloud:32.0.3@sha256:0ddb0f97ddd504f306a0fd1416b0fe65a875067ab31952d9b013a0c82e32d84e
    environment:
      # Space separated trusted domains
      # https://github.com/nextcloud/docker?tab=readme-ov-file#trusted-domains-trusted_domains
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.hayzen.uk"
      # Increase the PHP upload limit
      #
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html
      #
      # TODO: ensure caddy also supports this (request_body?)
      PHP_UPLOAD_LIMIT: 128G
      APACHE_BODY_LIMIT: 0
      # Settings for running behind reverse proxy
      # https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html
      TRUSTED_PROXIES: "127.0.0.1 172.16.0.0/12"
      OVERWRITEHOST: "nextcloud.hayzen.uk"
      OVERWRITECLIURL: "https://nextcloud.hayzen.uk"
      OVERWRITEPROTOCOL: "https"
    depends_on:
      - nextcloud-redis
    expose:
      - 80
    networks:
      - app-nextcloud
      - group-proxy
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      # Configuration
      - /var/cache/docker-compose-runner-user1000/nextcloud/html:/var/www/html
      # Note we mount into /usr/src/nextcloud as this is rsynced into the config dir
      # https://github.com/nextcloud/docker/blob/f2ab521657fe2e550cd39307c8dd3912eca7506d/docker-entrypoint.sh#L192
      - /etc/nextcloud/custom.config.php:/usr/src/nextcloud/config/custom.config.php:ro
      - /etc/nextcloud/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # PHP temp directory
      - /mnt/mapping-pool-user1000/data/app/nextcloud/tmp:/var/tmp/nextcloud/upload
      # External writable mounts
      #
      # TODO: mark items as writable
      - /mnt/mapping-pool-user1000/data/camera:/mnt/pool/data/camera:ro
      - /mnt/mapping-pool-user1000/data/files:/mnt/pool/data/files:ro
      - /mnt/mapping-pool-user1000/data/movies:/mnt/pool/data/movies:ro
      - /mnt/mapping-pool-user1000/data/music:/mnt/pool/data/music:ro
      - /mnt/mapping-pool-user1000/data/recordings:/mnt/pool/data/recordings:ro
      - /mnt/mapping-pool-user1000/data/shows:/mnt/pool/data/shows:ro
      - /mnt/mapping-pool-user1000/data/user:/mnt/pool/data/user:ro
      # External readonly mounts
      - /mnt/mapping-pool-user1000/data/documents:/mnt/pool/data/documents:ro
      - /mnt/mapping-pool-user1000/data/photostream:/mnt/pool/data/photostream:ro

  nextcloud-redis:
    image: docker.io/library/redis:8.4.0@sha256:47200b04138293fae39737e50878a238b13ec0781083126b1b0c63cf5d992e8d
    networks:
      - app-nextcloud
    restart: unless-stopped
