# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  bitwarden:
    image: ghcr.io/bitwarden/lite:2026.8.1@sha256:c30be950f4339c2224a2af2dacc5689271aecd52b54607594d28938188bc60ff
    env_file:
      - /etc/bitwarden/settings.env
    # https://bitwarden.com/help/environment-variables/
    environment:
      BW_DOMAIN: "bitwarden.hayzen.uk"
      # Use sqlite
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/vault.db"
      # Configure real IPs from traefik, group-proxy, and VPN tunnel
      BW_REAL_IPS: "172.20.20.0/16,172.28.228.128/25"
      # Disable account registration
      globalSettings__disableUserRegistration: true
      # Set user ids to 1000 manually as defaults as 911
      PGID: 1000
      PUID: 1000
    expose:
      - "8080"
    # Bitwarden requires at least 200M
    # https://bitwarden.com/help/install-and-deploy-unified-beta/#memory-usage
    #
    # However we have seen OOM at 512M, lets try 1024M
    mem_limit: 1024m
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # Bitwarden uses uid 1000, so use our mapped folder
      - /var/cache/docker-compose-runner-user1000/bitwarden/config:/etc/bitwarden

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.bitwarden.yml:/etc/traefik/dynamic/traefik.bitwarden.yml:ro
