# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  bitwarden:
    image: ghcr.io/bitwarden/lite:2026.1.0@sha256:d9a4e609e956ce2be7a97771145a3daac309576ade4dbf3bc9ed4db3f0fba470
    env_file:
      - /etc/bitwarden/settings.env
    # https://bitwarden.com/help/environment-variables/
    environment:
      BW_DOMAIN: "bitwarden.hayzen.uk"
      # Use sqlite
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/vault.db"
      # Disable account registration
      globalSettings__disableUserRegistration: true
    expose:
      - "8080"
    # Bitwarden requires at least 200M
    # https://bitwarden.com/help/install-and-deploy-unified-beta/#memory-usage
    #
    # However we have seen OOM at 512M, lets try 1024M
    mem_limit: 1024m
    networks:
      - group-proxy
    restart: unless-stopped
    volumes:
      # Bitwarden uses uid 1000, so use our mapped folder
      - /var/cache/docker-compose-runner-user1000/bitwarden/config:/etc/bitwarden
