# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.26.0@sha256:16685fbba37a21d403f5390b907d286e15b3086d26527269b4ad785f71f571e5
    expose:
      - 80
    networks:
      - group-proxy
    volumes:
      # Backup the database
      - /var/lib/docker-compose-runner/audiobookshelf/config:/config
      # We do not need to backup the podcasts content or metadata
      - /var/cache/docker-compose-runner/audiobookshelf/podcasts:/podcasts
      - /var/cache/docker-compose-runner/audiobookshelf/metadata:/metadata
      # TODO: could add audiobook storage and support
    environment:
      - TZ=Europe/London
