# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.29.0@sha256:dd4a3079d26bfe9f0ea63de3e3eff483dfa25fef05ef850a5a9d121dca3794b2
    expose:
      - 80
    networks:
      - group-proxy
    volumes:
      # Backup the database
      - /var/lib/docker-compose-runner/audiobookshelf/config:/config
      # We do not need to backup the podcasts content or metadata
      - /var/cache/docker-compose-runner/audiobookshelf/podcasts:/podcasts
      - /var/cache/docker-compose-runner/audiobookshelf/metadata:/metadata
      # TODO: could add audiobook storage and support
    environment:
      - TZ=Europe/London
