# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.33.0@sha256:41047b9985f9c38c92ae8b4b34ffd1d77fca36efdfe49c6b962ff2fc8ccae1e9
    expose:
      - 80
    networks:
      - group-proxy
    volumes:
      # Backup the database
      - /var/cache/docker-compose-runner/audiobookshelf/config:/config
      # We do not need to backup the podcasts content or metadata
      - /var/cache/docker-compose-runner/audiobookshelf/podcasts:/podcasts
      - /var/cache/docker-compose-runner/audiobookshelf/metadata:/metadata
      # TODO: could add audiobook storage and support
    environment:
      - TZ=Europe/London
