# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  paperless-broker:
    image: ghcr.io/valkey-io/valkey:9.1.1@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /var/cache/docker-compose-runner/paperless/broker-valkey:/data
    networks:
      - app-paperless
    restart: unless-stopped

  paperless-webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:3.0.4@sha256:3838b9a4260d23acc5bb63aed407138435e70b56e5806f4baa350ca184e57582
    environment:
      # No automatic consumption directory
      PAPERLESS_CONSUMER_DISABLE: true
      PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ correspondent }}/{{ created }} - {{ doc_pk }} - {{ title }}"
      PAPERLESS_OCR_LANGUAGE: eng
      # Additional languages to install
      PAPERLESS_OCR_LANGUAGES: jpn
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TIME_ZONE: "Europe/London"
      PAPERLESS_URL: https://paperless.hayzen.uk
      # Trust traefik, group-proxy, and VPN tunnel
      PAPERLESS_TRUSTED_PROXIES: "172.20.20.0/24,172.28.228.128/25"
    env_file:
      - /etc/paperless/settings_secrets.env
    expose:
      - 8000
    depends_on:
      - paperless-broker
    networks:
      - app-paperless
      - group-proxy
    volumes:
      # Where the database is stored
      - /var/cache/docker-compose-runner-user1000/paperless/data:/usr/src/paperless/data
      # Where documents are stored
      - /mnt/mapping-pool-user1000/data/documents:/usr/src/paperless/media
      # Where document_exporter can export to
      - /mnt/mapping-pool-user1000/data/app/paperless/export:/usr/src/paperless/export
    restart: unless-stopped

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.paperless.yml:/etc/traefik/dynamic/traefik.paperless.yml:ro
