# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  paperless-broker:
    image: docker.io/library/redis:8.4.0@sha256:47200b04138293fae39737e50878a238b13ec0781083126b1b0c63cf5d992e8d
    volumes:
      - /var/cache/docker-compose-runner/paperless/broker:/data
    networks:
      - app-paperless
    restart: unless-stopped

  paperless-webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.3@sha256:57ad9565bff3bdf2378ab1dcc21ea649dfd68ee58e0eeca2bfba0120a26563e8
    environment:
      # No automatic consumption directory
      PAPERLESS_CONSUMER_DISABLE: true
      PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ correspondent }}/{{ created }} - {{ doc_pk }} - {{ title }}"
      PAPERLESS_OCR_LANGUAGE: eng
      # Additional languages to install
      PAPERLESS_OCR_LANGUAGES: jpn
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TIME_ZONE: "Europe/London"
      PAPERLESS_URL: https://paperless.hayzen.uk
    env_file:
      - /etc/paperless/settings_secrets.env
    expose:
      - 8000
    depends_on:
      - paperless-broker
    networks:
      - app-paperless
      - group-proxy
    volumes:
      # Where the database is stored
      - /var/cache/docker-compose-runner-user1000/paperless/data:/usr/src/paperless/data
      # Where documents are stored
      - /mnt/mapping-pool-user1000/data/documents:/usr/src/paperless/media
      # Where document_exporter can export to
      - /mnt/mapping-pool-user1000/data/app/paperless/export:/usr/src/paperless/export
    restart: unless-stopped
