# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  caddy:
    links:
      - rathole
    volumes:
      # Caddy configuration file
      - /etc/caddy/sites/rathole.Caddyfile:/etc/caddy/sites/rathole.Caddyfile:ro

  rathole:
    image: docker.io/rapiz1/rathole:v0.5.0@sha256:a31b9178e985d4a84f46d4c3af6aa200ee0c5e7f821c7075a1f6669fb77392b1
    command: --server /etc/rathole/config.toml
    expose:
      # Bitwarden
      - "8080"
      # Immich
      - "8301"
      # Actual
      - "8506"
      # SFTPGo
      - "8880"
      # WebDav
      - "8890"
      # Jellyfin
      - "8896"
      # Audiobookshelf
      - "13378"
    ports:
      # Expose the server
      - "8333:8333"
      # Expose OpenVPN
      - "9194:9194"
    volumes:
      - /etc/rathole/config.toml:/etc/rathole/config.toml:ro
