# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

[server]
bind_addr = "0.0.0.0:8333"
default_token = "CHANGEME"

[server.services.actual]
bind_addr = "0.0.0.0:8506"

[server.services.audiobookshelf]
bind_addr = "0.0.0.0:13378"

[server.services.bitwarden]
bind_addr = "0.0.0.0:8080"

[server.services.bookstack]
bind_addr = "0.0.0.0:6875"

[server.services.glances]
bind_addr = "0.0.0.0:61208"

[server.services.immich]
bind_addr = "0.0.0.0:8283"

[server.services.jellyfin]
bind_addr = "0.0.0.0:8896"

[server.services.sftpgo]
bind_addr = "0.0.0.0:8880"

[server.services.webdav]
bind_addr = "0.0.0.0:8890"

[server.services.vikunja]
bind_addr = "0.0.0.0:3456"
