# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack:25.12.20251224@sha256:597cd4fc121f1d74c40e93cf7b0d5e1b3fc61af486a87cd65e2f86b0c0a5d914
    depends_on:
      - bookstack-database
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - /etc/bookstack/settings.env
      - /etc/bookstack/settings_secrets.env
    networks:
      - app-bookstack
      - group-proxy
    volumes:
      - /var/cache/docker-compose-runner-user1000/bookstack/config:/config
      # Items we want to backup
      #
      # .env
      - /var/lib/docker-compose-runner-user1000/bookstack/env:/config/www/.env
      # storage/backups/
      - /var/lib/docker-compose-runner-user1000/bookstack/backups:/config/backups
      # storage/uploads/files
      - /var/lib/docker-compose-runner-user1000/bookstack/files:/config/www/files
      # storage/uploads/images
      - /var/lib/docker-compose-runner-user1000/bookstack/images:/config/www/images
      # themes
      - /var/lib/docker-compose-runner-user1000/bookstack/themes:/config/www/themes
      # public/uploads
      - /var/lib/docker-compose-runner-user1000/bookstack/uploads:/config/www/uploads
    expose:
      - 80
    restart: unless-stopped

  bookstack-database:
    container_name: bookstack_database
    image: ghcr.io/linuxserver/mariadb:11.8.8@sha256:fb38247d1a4440239b2c62f0084c5285302715777268a92f61f77406dbc3552e
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - /etc/bookstack/settings.env
      - /etc/bookstack/settings_secrets.env
    expose:
      - 3306
    networks:
      - app-bookstack
    volumes:
      - /etc/bookstack/backup.sh:/usr/local/bin/bookstack-backup:ro
      - /var/cache/docker-compose-runner-user1000/bookstack/database:/config
      - /var/lib/docker-compose-runner-user1000/bookstack/database:/var/lib/docker-compose-runner/bookstack/database
    restart: unless-stopped

  traefik:
    volumes:
      - /etc/traefik/dynamic/traefik.bookstack.yml:/etc/traefik/dynamic/traefik.bookstack.yml:ro
