# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

# When using a Debian install via OVH this information was collected via
#
# ```console
# sudo su
# sh <(curl -L https://nixos.org/nix/install) --daemon
# sudo su
# nix-env -iE "_: with import <nixpkgs/nixos> { configuration = {}; }; with config.system.build; [ nixos-generate-config ]"
# nixos-generate-config --no-filesystems --root /mnt
# ```

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-3712864cdae2.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6be2f64815bc.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-77b86f5b676c.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6c7dc59.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7e2805c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9d12282.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaf48364.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe5af1a6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
