# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

services:
  actual:
    image: docker.io/actualbudget/actual-server:24.7.0@sha256:12cb8d9b8e653b66e185360e980c08e90f8c1f40bf4fb34dcb90eb270329d996
    expose:
      - "5006"
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/actual/data:/data

  bitwarden:
    image: docker.io/bitwarden/self-host:2024.6.1-beta@sha256:3aec1bb03bd24e03cefba9f3902a33f88d4b56d268e9d515d43ef5f222daa318
    env_file:
      - /etc/bitwarden/settings.1.env
    # https://bitwarden.com/help/environment-variables/
    environment:
      BW_DOMAIN: "bitwarden.ahayzen.com"
      # Use sqlite
      BW_DB_PROVIDER: "sqlite"
      BW_DB_FILE: "/etc/bitwarden/vault.db"
      # We are using userns so run as root in the container but unpriv outside
      PUID: 0
      PGID: 0
      # Disable account registration
      #
      # Allow for now to setup accounts
      globalSettings__disableUserRegistration: true
      # TODO: https?
    expose:
      - "8080"
    mem_limit: 1024m
    restart: unless-stopped
    volumes:
      - /var/lib/docker-compose-runner/bitwarden/config:/etc/bitwarden

  rathole:
    image: docker.io/rapiz1/rathole:v0.5.0@sha256:a31b9178e985d4a84f46d4c3af6aa200ee0c5e7f821c7075a1f6669fb77392b1
    command: --client /etc/rathole/config.toml
    links:
      - actual
      - bitwarden
    volumes:
      - /etc/rathole/config.1.toml:/etc/rathole/config.toml:ro
