# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

name: nix flake check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v5
      - name: nix flake check
        run: nix flake --option sandbox false check -L
