# SPDX-FileCopyrightText: Andrew Hayzen <ahayzen@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v3

  flake-checker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v5

  nix-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: nix fmt
        run: nix fmt
      - name: git diff
        run: git diff --exit-code

  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # Shellcheck should already be installed on github runners
      - name: install shellcheck
        run: sudo apt install --yes shellcheck
      - name: shellcheck
        run: shellcheck scripts/*.sh

  nix-flake-check:
    # Run after pre checks
    needs: [license-check, flake-checker, nix-fmt, shellcheck]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: nix flake check
        run: nix flake --option sandbox false check -L
